export const INITIAL_DATA_CONSTANT = {
  PETERNAKAN: {
    POPULASI_TERNAK_SAPI: 17074,
    POPULASI_TERNAK_KAMBING: 1884460,
    POPULASI_TERNAK_AYAM: 10429569,
  },
  PERIKANAN: {
    LUAS_AREA_PERIKANAN: 18748,
  },
  LAND_COVER: {
    INDUSTRIAL_LAND: 7440,
    HOUSING_LAND: 24121,
    FOREST_AREA: 7104,
    AGRICULTURE_AREA: 108695,
    OTHER_LAND: 44504,
    AVAILABLE_LAND: 191864,
  },
  ENERGY: {
    PANEL_EFICIENCY: 90,
    DAYA_MAKSIMUM: 450,
    IRADIASI_STANDARD: 1000,
    LUAS_PER_PANEL: 2,
    EFISIENSI_MODUL: 23,
    IRADIASI_HARIAN_RERATA: 4.5,
    PRODUKSI_LISTIK_HARIAN_RERATA: 0.91125,
    PRODUKSI_LISTRIK_TAHUNAN_RERATA: 332.60625,
    KDBi: 0.5,
    KDBh: 0.7,
    PRESENTASI_AREA_ATAP_INDUSTRI: 0.6,
    PRESENTASI_AREA_ATAP_RUMAHAN: 0.6,
  },
};

export const INITIAL_DATA_CONSTANT_SIDOWARJO = {
  PETERNAKAN: {
    POPULASI_TERNAK_SAPI:  13500 ,
    POPULASI_TERNAK_KAMBING:  75000,
    POPULASI_TERNAK_AYAM:  545000,
  },
  PERIKANAN: {
    LUAS_AREA_PERIKANAN: 15000,
  },
  LAND_COVER: {
    INDUSTRIAL_LAND:  2452,
    HOUSING_LAND:  17148 ,
    FOREST_AREA:  1028 ,
    AGRICULTURE_AREA:  43498 ,
    OTHER_LAND:  8243 ,
    AVAILABLE_LAND: 72368.79,
  },
  ENERGY: {
    PANEL_EFICIENCY: 0,
    DAYA_MAKSIMUM: 0,
    IRADIASI_STANDARD: 0,
    LUAS_PER_PANEL: 0,
    EFISIENSI_MODUL: 0,
    IRADIASI_HARIAN_RERATA: 0,
    PRODUKSI_LISTIK_HARIAN_RERATA: 0,
    PRODUKSI_LISTRIK_TAHUNAN_RERATA: 0,
    KDBi: 0,
    KDBh: 0,
    PRESENTASI_AREA_ATAP_INDUSTRI: 0,
    PRESENTASI_AREA_ATAP_RUMAHAN: 0,
  },
};