export const FOOD_STANDARD = {
  RICE: 79.2,
  MEIZE: 20,
};

export const FOOD_DEMAND_SIDE = {
  POPULATION_INITIAL: 950000,
  POPULATION_GROWTH: 0.0132,
  RICE_DEMAND_PER_PERSON: 79.2,
  CONVERTION_FACTOR_RICE: 0.63,
  CONVERTION_FACTOR_GKG: 0.85,
};

export const AGRICULTURE_PRODUCTION_DEMAND = {
  INPARI_32: {
    AREA_HA: 15000,
    CONVERSION_RATE: 0.0132,
  },
  CIHERANG: {
    AREA_HA: 25000,
    CONVERSION_RATE: 0.0088,
  },
  MEKONGGA: {
    AREA_HA: 32000,
    CONVERSION_RATE: 0.017,
  },
  HIPPASERIES: {
    AREA_HA: 12500,
    CONVERSION_RATE: 0.012,
  },
  LOKAL: {
    AREA_HA: 7500,
    CONVERSION_RATE: 0.021,
  },
};

export const FERTILIZER_INPUTS = {
  PERCENTAGE_OF_CHEMICAL_FERTILIZER: 30,
  RATIO_ORGANIC: 17,
};

export const RAINFALL = {
  ANNUAL_RAINFALL: 150,
  AREA_SIZE: 110,
};

export const FOOD_AND_YIELD = {
  INPARI_32: {
    BASE_YIELD: 5.5,
    WATER_CONSUMPTION_UNIT: 7969,
    PLAN_TO_HARVEST_DURATION: 117,
    PLANTING_SESSION_PER_YEAR: 2,
    CHEMICAL_FERTILIZER_DEMAND: 200,
    ORGANIC_FERTILIZER_DEMAND: 3.4,
    POTENTIAL_PRODUCTIVITY: 11,
    ENERGY_DEMAND: {
      LAND_PROCESSING: 2000,
      PLANTING_AND_MAINTENANCE: 1000,
      IRRIGATION: 2000,
      HARVEST_AND_TRANSPORT: 2200,
    },
  },
  CIHERANG: {
    BASE_YIELD: 6,
    WATER_CONSUMPTION_UNIT: 7969,
    PLAN_TO_HARVEST_DURATION: 112,
    PLANTING_SESSION_PER_YEAR: 2,
    CHEMICAL_FERTILIZER_DEMAND: 180,
    ORGANIC_FERTILIZER_DEMAND: 3.06,
    POTENTIAL_PRODUCTIVITY: 12,
    ENERGY_DEMAND: {
      LAND_PROCESSING: 1500,
      PLANTING_AND_MAINTENANCE: 920,
      IRRIGATION: 3500,
      HARVEST_AND_TRANSPORT: 1800,
    },
  },
  MEKONGGA: {
    BASE_YIELD: 6,
    WATER_CONSUMPTION_UNIT: 7969,
    PLAN_TO_HARVEST_DURATION: 117,
    PLANTING_SESSION_PER_YEAR: 2,
    CHEMICAL_FERTILIZER_DEMAND: 180,
    ORGANIC_FERTILIZER_DEMAND: 3.06,
    POTENTIAL_PRODUCTIVITY: 12,
    ENERGY_DEMAND: {
      LAND_PROCESSING: 1500,
      PLANTING_AND_MAINTENANCE: 920,
      IRRIGATION: 3500,
      HARVEST_AND_TRANSPORT: 1800,
    },
  },
  HIPASERRIES: {
    BASE_YIELD: 9,
    WATER_CONSUMPTION_UNIT: 7969,
    PLAN_TO_HARVEST_DURATION: 105,
    PLANTING_SESSION_PER_YEAR: 2,
    CHEMICAL_FERTILIZER_DEMAND: 300,
    ORGANIC_FERTILIZER_DEMAND: 5.1,
    POTENTIAL_PRODUCTIVITY: 18,
    ENERGY_DEMAND: {
      LAND_PROCESSING: 2300,
      PLANTING_AND_MAINTENANCE: 1165,
      IRRIGATION: 6000,
      HARVEST_AND_TRANSPORT: 2500,
    },
  },
  LOKAL: {
    BASE_YIELD: 3,
    WATER_CONSUMPTION_UNIT: 7969,
    PLAN_TO_HARVEST_DURATION: 130,
    PLANTING_SESSION_PER_YEAR: 2,
    CHEMICAL_FERTILIZER_DEMAND: 100,
    ORGANIC_FERTILIZER_DEMAND: 1.7,
    POTENTIAL_PRODUCTIVITY: 6,
    ENERGY_DEMAND: {
      LAND_PROCESSING: 1100,
      PLANTING_AND_MAINTENANCE: 750,
      IRRIGATION: 3000,
      HARVEST_AND_TRANSPORT: 1000,
    },
  },
};

export const ENERGY_INPUT_FOR_PRODUCTION = {
  SEED: 438.31,
  FERTILIZER: 11484.84,
  PESTICIDE: 3681.36,
  HUMAN_LABOUR: 1425.48,
  TRACTOR: 918.47,
  SOLAR_FUEL: 574.09,
};
