import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderComponent from "@/stores/provider";
import Navigation from "@/components/organisms/Navigation";
import Footer from "@/components/organisms/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WFE Nexus - v0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-h-[100dvh] w-full overflow-hidden flex flex-col justify-between">
          <Navigation />
          <div className="flex grow  w-full">
            <ProviderComponent>{children}</ProviderComponent>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
